#### 임베딩


In [2]:
import tensorflow as tf


In [3]:
sentences = ['Today is happy',
             'Today is a rainy day',
             'I am so happy']

In [4]:
num_size = 10
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = num_size, oov_token="<OOV>")

In [5]:
tokenizer.fit_on_texts(sentences)

In [7]:
word_index = tokenizer.index_word
word_index

{1: '<OOV>',
 2: 'today',
 3: 'is',
 4: 'happy',
 5: 'a',
 6: 'rainy',
 7: 'day',
 8: 'i',
 9: 'am',
 10: 'so'}

In [8]:
rets = tokenizer.texts_to_sequences(sentences)

In [9]:
rets

[[2, 3, 4], [2, 3, 5, 6, 7], [8, 9, 1, 4]]

In [14]:
lengths = [len(x) for x in rets]
token_length = max(lengths)
token_length

5

In [16]:
rets2 = tf.keras.preprocessing.sequence.pad_sequences(rets, maxlen = token_length, padding = 'post',truncating= 'post')

In [44]:
rets2
#임베딩 시
#문장 개수, 패딩 값, Voca개수 차원
#예시의 경우 (3, 5, 9)



array([[2, 3, 4, 0, 0],
       [2, 3, 5, 6, 7],
       [8, 9, 1, 4, 0]])

In [63]:
model = tf.keras.Sequential()

In [64]:
model.add(tf.keras.layers.Embedding(input_dim = num_size, output_dim = 3, input_length = 5))
#
#input_length 토큰의 길이 5

In [65]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_16 (Embedding)     (None, 5, 3)              30        
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________


In [67]:
model.compile(loss='mse')
out = model.predict(rets2)
out

array([[[-0.00817738, -0.00520017,  0.00977758],
        [-0.01986757, -0.02904822,  0.04731525],
        [-0.03019768, -0.04201747, -0.01442677],
        [ 0.02722864,  0.04424641, -0.02831835],
        [ 0.02722864,  0.04424641, -0.02831835]],

       [[-0.00817738, -0.00520017,  0.00977758],
        [-0.01986757, -0.02904822,  0.04731525],
        [ 0.04778106,  0.0441029 ,  0.02805469],
        [ 0.0415099 ,  0.0431441 ,  0.03111564],
        [ 0.02447305, -0.03673171, -0.00569488]],

       [[-0.02692952, -0.01616374,  0.0411003 ],
        [ 0.02477554, -0.04478332,  0.03425277],
        [-0.03660975,  0.04006792, -0.017542  ],
        [-0.03019768, -0.04201747, -0.01442677],
        [ 0.02722864,  0.04424641, -0.02831835]]], dtype=float32)

array([[[-2.0646382e-02,  1.7898452e-02,  4.2640343e-03],
        [ 1.3928164e-02, -2.3225153e-02, -3.9167415e-02],
        [-8.3938725e-03,  1.5612792e-02, -2.3467887e-02],
        [-1.2034915e-02, -3.0778218e-02,  4.4940200e-02],
        [-1.2034915e-02, -3.0778218e-02,  4.4940200e-02]],

       [[-2.0646382e-02,  1.7898452e-02,  4.2640343e-03],
        [ 1.3928164e-02, -2.3225153e-02, -3.9167415e-02],
        [-2.4972379e-02, -1.7951928e-02,  1.7040286e-02],
        [-1.5903316e-02,  3.0650441e-02, -2.0604515e-02],
        [-3.9624523e-02, -1.8018961e-02,  4.0206898e-02]],

       [[ 3.8841259e-02,  5.8468468e-03, -4.8200455e-02],
        [ 1.6783383e-02,  4.9900804e-02,  4.9619261e-02],
        [ 1.4584158e-02,  9.3282834e-03,  3.7945807e-05],
        [-8.3938725e-03,  1.5612792e-02, -2.3467887e-02],
        [-1.2034915e-02, -3.0778218e-02,  4.4940200e-02]]], dtype=float32)

In [69]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim = 5, output_dim = 3, input_length =  5))
model.compile(loss='mse')
out = model.predict(rets2)
out
#input_length 토큰의 길이 5

InvalidArgumentError:  indices[1,2] = 5 is not in [0, 5)
	 [[node sequential_15/embedding_18/embedding_lookup (defined at C:\Users\dddf\AppData\Local\Temp\ipykernel_19892\946946718.py:4) ]] [Op:__inference_predict_function_1463]

Errors may have originated from an input operation.
Input Source operations connected to node sequential_15/embedding_18/embedding_lookup:
 sequential_15/embedding_18/embedding_lookup/1455 (defined at c:\Users\dddf\anaconda3\envs\deeplang\lib\contextlib.py:112)

Function call stack:
predict_function


model2.su